name: Plastic4trade
description: A new Flutter project.
publish_to: "none"

version: 1.0.4+2

environment:
  sdk:
    # ">=2.19.2 <3.0.0"
    ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: any
  shared_preferences: any
  flutter_otp_text_field: ^1.1.1
  file_picker: ^5.2.7
  url_launcher: ^6.0.10
  intl: any
  flutter_slidable: ^3.1.2
  image_picker: ^0.8.9
  flutter_image_compress: any
  share: any
  package_info_plus: any
  flutter_html: any
  firebase_messaging: ^14.7.0
  firebase_core: any
  flutter_local_notifications: ^9.0.0
  flutter_pdfview: ^1.3.1
  device_info_plus: any
  country_calling_code_picker: ^2.0.1
  android_id: any
  syncfusion_flutter_charts: ^27.1.56
  cached_network_image: ^3.2.3
  connectivity_plus: ^5.0.2
  info_popup: ^4.3.1
  flutter_typeahead: ^4.8.0
  firebase_analytics: ^10.10.2
  shimmer: ^3.0.0
  typed_data: ^1.3.2
  lottie: ^3.0.0
  gtm: ^0.1.3
  flutter_location_search: ^1.1.4
  flutter_google_places_hoc081098: any
  google_tag_manager: ^0.1.0
  google_maps_flutter: any
  facebook_app_events: ^0.19.1
  razorpay_flutter: ^1.3.7
  path_provider: ^2.1.4
  in_app_update: ^4.2.3
  youtube_player_flutter: ^9.1.0
  dio: ^5.7.0
  firebase_dynamic_links: ^5.5.7
  app_links: ^6.3.2
  smart_auth: ^2.0.0
  pinput: ^5.0.0
  scrollable_tab_view: ^1.0.13
  # permission_handler: ^11.3.1
  # flutter_contacts: ^1.1.9+2
  

dependency_overrides:
  rxdart: ^0.28.0  # Or the version that fits your project needs
  http: ^0.13.4

  #share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  getwidget: ^5.0.0
  marquee: ^2.2.3
  email_validator: any
  flutter_rating_bar: any
  youtube_player_iframe: ^4.0.4
  badges: ^3.0.2
  http: any
  slide_switcher: ^1.1.2
  image_cropper: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/plastic4trade logo final.png
    - assets/plastic4trade logo final 1 (2).png
    - assets/image 1.png
    - assets/image 2.png
    - assets/Vector.png
    - assets/Ellipse 1.png
    - assets/Vector (1).png
    - assets/Notification.png
    - assets/homemsg.png
    - assets/Home.png
    - assets/sale.png
    - assets/Buyer.png
    - assets/more.png
    - assets/news.png
    - assets/back.png
    - assets/search.png
    - assets/location.png
    - assets/image 3.png
    - assets/like.png
    - assets/Send.png
    - assets/hidepassword.png
    - assets/homeprice.png
    - assets/bag-2.png
    - assets/clipboard-text.png
    - assets/directbox-default.png
    - assets/document-text.png
    - assets/play-circle.png
    - assets/forward.png
    - assets/box.png
    - assets/shop.png
    - assets/shopping-cart.png
    - assets/video.png
    - assets/bag-tick.png
    - assets/heart-circle.png
    - assets/profile-2user.png
    - assets/star.png
    - assets/premium_mem.png
    - assets/award.png
    - assets/send-2.png
    - assets/whatsapp.png
    - assets/youtube.png
    - assets/Telegram.png
    - assets/Twitter.png
    - assets/instagram.png
    - assets/linkdin.png
    - assets/LinkedIn.png
    - assets/facebook.png
    - assets/Facebook (1).png
    - assets/YouTube (1).png
    - assets/Twitter.png
    - assets/edit.png
    - assets/edit1.png
    - assets/user.png
    - assets/call.png
    - assets/verify.png
    - assets/sms.png
    - assets/star.png
    - assets/hori_line.png
    - assets/add_document.png
    - assets/password.png
    - assets/forgetPassword.png
    - assets/Otpverification.png
    - assets/flash.png
    - assets/Delete.png
    - assets/suspended.png

    - assets/delete.png
    - assets/addphoto1.png
    - assets/fav.png
    - assets/call1.png
    - assets/contactus_back.png
    - assets/contactus_loc.png
    - assets/msg1.png
    - assets/delete1.png
    - assets/delete2.png
    - assets/Setting.png
    - assets/PaidPost.png
    - assets/Play.png
    - assets/like1.png
    - assets/send2.png
    - assets/view1.png
    - assets/user_chat.png
    - assets/follow1.png
    - assets/web.png
    - assets/verify1.png
    - assets/trust.png
    - assets/Premium1.png
    - assets/Premium2.png
    - assets/add_image.png
    - assets/add_doc.png
    - assets/share1.png
    - assets/list_data.png
    - assets/diagram.png
    - assets/show.png
    - assets/Line.png
    - assets/account.png
    - assets/xIcon.jpg
    - assets/appLogo.jpeg
    - assets/image_animation.json
    - assets/loading_animation.json
    - assets/Dot_Lottie.json
    - assets/Dotsanimation.json
    
    - assets/bussines_profile.png

    - assets/adWithUs1.jpg
    - assets/adWithUs2.jpg
    - assets/adWithUs3.png
    - assets/adWithUs4.jpg
    - assets/adWithUs5.jpg
    - assets/plastic4trade _logo_dialog.png
    - assets/Call2.png
    - assets/Untrusted.png
    - assets/Unverified.png



  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonst/Metropolis-Regular.otf
        - asset: assets/fonst/Metropolis-Black.otf
        - asset: assets/fonst/Metropolis-SemiBold.otf
